### ISSUE TITLE
BartyCrouch:  Could not parse syntax tree of Swift file.

### ISSUE THREAD

**Issue by trujamal** [FlineDev/BartyCrouch#201] opened 2020-09-23 06:18 UTC
## Expected Behavior
No warning's should show

## Actual Behavior
Two warnings shows as follows

-  BartyCrouch:  Could not find 'SupportedLanguage' enum within 'BartyCrouch' enum within path.
- BartyCrouch:  Could not parse syntax tree of Swift file. #199 

## Steps to Reproduce the Problem

  1.  Open any project on Xcode 12.0 (12A7209)
  2. Proceed to build project with implmentation
  3. Then in the build warnings you will get the following errors [September 23rd, 2020]

## Specifications

  - Version: iOS 14
  - Platform: Mac OS
  - IDE Version:  Xcode 12.0 (12A7209)

## Example
<img width="296" alt="Screen Shot 2020-09-23 at 1 17 46 AM" src="https://user-images.githubusercontent.com/16698402/93973902-994b4980-fd3a-11ea-979a-0fcc7671d5f5.png">

**Comment by AdminAnticaptcha** [comment] 2020-09-24 16:22
Same here

**Comment by Kondamon** [comment] 2022-03-15 21:03
@Jeehut: The same error happens again with Xcode 13.3 and Swift 5.6.

**Comment by Jeehut** [comment] 2022-03-15 21:06
@Kondamon Thank you for reporting, I'll have a look tomorrow.

**Comment by Jeehut** [comment] 2022-03-16 11:23
I just had a look into this and I think I need to update the [swift-syntax](https://github.com/apple/swift-syntax) dependency to the new version supporting Swift 5.6. I just tried, but unfortunately there's currently [a bug](https://bugs.swift.org/browse/SR-15989) in the latest release of swift-syntax which [is being worked](https://github.com/apple/swift-syntax/pull/372) on at the moment. Other tools like [swift-format](https://github.com/apple/swift-format/pull/281) are running into the same issue and can't make a new release.

I hope (and I'm sure) this will be fixed in a matter of days. I'm reopening this issue until then. If you highly depend on BartyCrouch in your project, you might want to hold off on updating to Xcode 13.3 until this has been fixed. I'm sorry, but there's nothing I can do at the moment. 🤷

**Comment by FlineDevPublic** [comment] 2022-03-18 11:48
@trujamal @AdminAnticaptcha @Kondamon @NickAtGit I just [released version 4.10.0](https://github.com/Flinesoft/BartyCrouch/releases/tag/4.10.0) with a fix. Should be live once https://github.com/Homebrew/homebrew-core/pull/97188 is merged. 🎉 

---
_This comment was written during my regular **Open Source live stream on [Twitch](https://www.twitch.tv/jeehut)**. Follow me there to support my work!_

**Comment by Sn0wfreezeDev** [comment] 2022-09-08 14:07
Getting now the same error with Xcode 14 RC, all the betas were fine and not producing this issue. :/

**Comment by Jeehut** [comment] 2022-09-08 14:51
@Sn0wfreezeDev Thank you for reporting this. Unfortunately, BartyCrouch is depending on [swift-syntax](https://github.com/apple/swift-syntax) which always breaks when using a higher Swift version (Xcode 14 ships with Swift 5.7). Until there's a release of swift-syntax with Swift 5.7 support, I can't make a release with a fix.

This is one of the reasons why I worked on a successor to BartyCrouch which does not have any such dependencies and improved on many other things as well and is much easier to work with thanks to it having a GUI. While it's officially still in beta, it's very close to release and I've put a lot more testing into it than into BartyCrouch (of course I reused some portion of BartyCrouch, but improved it). This might be a good time to switch to ReMafoX or at least testing it out:
https://github.com/FlineDev/ReMafoX/releases

Don't forget to send in any feedback in case you encounter problems, I'm currently focusing on finding edge cases before the public release.

**Comment by Sn0wfreezeDev** [comment] 2022-09-09 07:54
Thanks for showing that, I will definitely have a look at it and try to change our current workflow to using ReMaFox :)

**Comment by NickAtGit** [comment] 2022-09-09 18:53
Temporary fix to use Xcode 14 and BartyCrouch: Leave Xcode 13.x.x with an unchanged name of Xcode.app in your applications folder.

**Comment by Jeehut** [comment] 2022-10-06 06:08
A fixed [swift-syntax release](https://github.com/apple/swift-syntax/releases/tag/0.50700.1) has been made just 20 hours ago and I already sent over a 4.12.1 update to Homebrew. BartyCrouch should be working for Xcode 14 as soon as https://github.com/Homebrew/homebrew-core/pull/112470 is merged.

Note that swift-syntax now includes `_InternalSwiftSyntaxParser.dylib` as a binary framework dependency. So hopefully we should not run into the same issue with the release of Swift 5.8 / Xcode 15. 🤞

**Comment by Jeehut** [comment] 2022-10-08 11:29
Alright, version 4.12.1 also did not go through, but then someone from the [swift-syntax](https://github.com/apple/swift-syntax/issues/884) team helped me by pointing me a solution of statically linking the `.dylib` so we don't have these yearly Xcode upgrade issues in the future. I [released 4.13.0](https://github.com/FlineDev/BartyCrouch/releases/tag/4.13.0) and this time, it actually has gone through and is now available for `brew upgrade bartycrouch`!

Please try it out and report if you find any issues.

**Comment by Kondamon** [comment] 2022-10-08 16:13
@Jeehut, thank you for your effort fixing this issue. I have tried 4.13.0 now with Version 14.1 beta 3 (14B5033e), most errors are gone. However, I receive `warning: BartyCrouch:  Could not parse syntax tree of Swift file.` for all Swift files that are located within "Project/SupportingFIles" as given in the update.transform task. With Xcode 13 everything worked without any issues.

```
/Users/.../pgm/vb/Project/Supporting Files/Constants.swift:  warning: BartyCrouch:  Could not parse syntax tree of Swift file.
/Users/.../pgm/vb/Project/Supporting Files/AppCheckProviderFactory.swift:  warning: BartyCrouch:  Could not parse syntax tree of Swift file.
/Users/.../pgm/vb/Project/Supporting Files/BartyCrouch.swift:  warning: BartyCrouch:  Could not parse syntax tree of Swift file.
/Users/.../pgm/vb/Project/Supporting Files/MainApp.swift:  warning: BartyCrouch:  Could not parse syntax tree of Swift file.
/Users/.../pgm/vb/Project/Supporting Files:  warning: BartyCrouch:  Could not find 'SupportedLanguage' enum within 'BartyCrouch' enum within path.
```

```
[update]
tasks = ["transform", "normalize"]

[update.transform]
codePaths = ["Project"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
localizablePaths = ["."]
transformer = "swiftgenStructured"
supportedLanguageEnumPath = "Project/Supporting Files"
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
paths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
duplicateKeys = true
emptyValues = true
```

**Comment by Jeehut** [comment] 2022-10-10 09:23
@Kondamon Hmm ... thank you for informing me about this. Weird, it should use the statically linked version now, so the Xcode version shouldn't matter anymore. Does this also happen on non-beta Xcode 14.0?

**Comment by hsalminen** [comment] 2022-10-11 07:54
@Jeehut I can confirm that the issue reproduces with non-beta version of Xcode as well (Version 14.0.1 (14A400)).

`warning build: BartyCrouch:  Could not parse syntax tree of Swift file.`

I also see another warning which is most likely related to the same issue.

`warning build: BartyCrouch:  Could not find 'SupportedLanguage' enum within 'BartyCrouch' enum within path.`

BartyCrouch version: 4.13.0

**Comment by NickAtGit** [comment] 2022-10-11 08:12
This workaround still works: 
https://github.com/FlineDev/BartyCrouch/issues/201#issuecomment-1242350767

**Comment by hsalminen** [comment] 2022-10-11 08:18
@Jeehut thanks for the update, really appreciate your effort! The new project seems super interesting but as you mentioned it is not for the same use case. The BartyCrouch is a perfect fit for our setup! 😎

@NickAtGit thanks for letting us know that the workaround is still valid!

**Comment by Sn0wfreezeDev** [comment] 2022-10-14 11:47
I found another _dirty_ quick fix. But be warned that this will ignore **all** warnings and errors from bartycrouch: 
```
bartycrouch update -x > /dev/null
```

**Comment by mshibanami** [comment] 2022-10-15 03:35
swift-syntax 0.50700.0 might be what BartyCroush should use for now, as the release note of 0.50700.1, which BartyCrouch currently uses, mentions this:

> ⚠️ Important: This release of SwiftSyntax is incompatible with the parser library included in the swift-5.7-RELEASE toolchain.
> https://github.com/apple/swift-syntax/releases/tag/0.50700.1

I cloned BartyCrouch repo, changed (reverted) swift-syntax from 0.50700.1 to 0.50700.0 in `Package.swift`, ran `swift build -c release`, and called `/path/to/BartyCrouch/.build/release/bartycrouch update` in my app's repo. Then the errors were gone, and my Code Transform task correctly worked with Xcode 14.0.1.

**Comment by mkcpb** [comment] 2022-12-13 17:41
I reproduce issue on Xcode(14.1) and Xcode(13.4.1). BartyCrouch version 4.13.0. Any solutions?

**Comment by Jeehut** [comment] 2022-12-14 12:33
I just made another release `4.14.0` with another change to how `lib_InternalSwiftSyntaxParser.dylib` is linked into BartyCrouch, hoping that this time I got the linking right (this is my 5th try for Xcode 14, I think). I am now copying the dylib from the SwiftSyntax dependency into the `/lib` directory and adjusting the rpath as suggested in [this article](https://www.smileykeith.com/2021/03/03/editing-rpaths/). I'm really hoping that the release [will go through on Homebrew](https://github.com/Homebrew/homebrew-core/pull/118139) and things will work for all users now.

Closing this tentatively. Fingers crossed that it works this time. 🤞 
You should be able to get the new version via `brew upgrade bartycrouch` once https://github.com/Homebrew/homebrew-core/pull/118139 is merged.

**Closed by Jeehut** 2022-12-14 12:33 UTC
Labels: bug

**Comment by Jeehut** [comment] 2022-12-19 08:24
FYI: Version `4.14.0` is now available via Homebrew (`brew upgrade bartycrouch`).
Please report if you still find any issues when using BartyCrouch with Xcode 14 (or any other version, it shouldn't matter).
