### ISSUE TITLE
Translate successful but no output for Storyboards Main.string file 

### ISSUE THREAD

**Issue by MarinaHuber** [FlineDev/BartyCrouch#252] opened 2022-05-19 07:42 UTC
## Expected Behavior
When building script and using translate, I would expect to see some Croatian translations for the Main.string
I am NOT using "code" and Localizable.string but just plain user-facing text in Main.string for testing purposes 
Also when running Azure api all works with GLOBAL region:

```
> curl -X POST "https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&to=hr" \
>      -H "Ocp-Apim-Subscription-Key: <KEY-FROM-TRANSLATOR>" \
>      -H "Content-Type: application/json" \
>      -d "[{'Text':'Hello, what is your name?'}]"
```

## Actual Behavior
Script runs success but no translate, and no idea how to debug it.
`/Users/user/Desktop/stuff/Whats-the-SkyCast/WeatherOnTheMap/Supporting files/en.lproj/Main.strings:  success: BartyCrouch:  Successfully translated 0 values in 0 files.`

<img width="809" alt="Screenshot 2022-05-19 at 08 54 53" src="https://user-images.githubusercontent.com/7971194/169236794-3cd6e925-7dfe-4827-965d-d6e85af726a7.png">

## Steps to Reproduce the Problem

  1. File .toml looks pretty basic but I did play with paths for the `translate` config   

[update]
tasks = ["interfaces", "code", "transform", "normalize", "translate"]

[update.interfaces]
paths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]

[update.code]
codePaths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
localizablePaths = ["."]
defaultToKeys = false
additive = true
unstripped = false
plistArguments = true
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]

[update.transform]
codePaths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
localizablePaths = ["."]
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
paths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
duplicateKeys = true
emptyValues = true

[update.translate]
paths = ["WeatherOnTheMap/Supporting files"]
translator = "microsoftTranslator"
secret = "Key-From-Translator"
sourceLocale = "en"

Is there something I can configure for only storyboard .strings that I am missing? I couldn't find it in the Issues or on web.
## Specifications
  - Version: 4.10.2
  - Platform: iOS 15.2
  - IDE Version: Xcode 13.2

**Comment by Jeehut** [comment] 2022-05-19 23:07
@MarinaHuber Thank you for reporting this issue. To help you, I need more information. Can you send me a screenshot of your file structure, including the `Main.strings` file in the language you expect it to be translated to and the `Main.strings` file in the source language `en`. Also, have you tried translating to other languages or is Croatian the only other language you have set up? That would help to know if its an issue with the language specifically, your file structure or the tool

**Comment by MarinaHuber** [comment] 2022-05-25 09:09
@Jeehut thank you for reaching out! here is the slightly different set-up but never the less nothing gets translated it is  "Hello world" project with the custom .toml file. I would expect that my Localizable.string (Spanish) on a **build** gets translated. Also I need to use @Designables to localize the Storyboard elements.
`Localizable.strings:  success: BartyCrouch:  Successfully translated 0 values in 0 files.
`
[translations-demo.zip](https://github.com/FlineDev/BartyCrouch/files/8769575/translations-demo.zip)

**Comment by FlineDevPublic** [comment] 2022-05-27 15:06
@MarinaHuber I just had a look at this during my stream and explained in detail why those warnings or errors are being shown. I'll link to the exact time code later, but in short, those errors come from an Apple tool, not from BartyCrouch. And neither Apple nor I can fix the root cause. But to remove the errors, you can simply exclude the subpath `"Helpers"` from the `[update.code]` task, see here:
![Screen Shot 2022-05-27 at 17 03 20](https://user-images.githubusercontent.com/97410916/170726812-29b5db1e-99a3-4fd0-9a33-7fce42711f2b.png)

Closing this as you already stated you could solve it yourself.

---
_This comment was written during my regular **Open Source live stream on [Twitch](https://www.twitch.tv/jeehut)**. Follow me there to support my work!_

**Closed by FlineDevPublic** 2022-05-27 15:06 UTC
Labels: bug
